workflows:
  my-workflow:
    scripts:
      - name: Build Android APK
        working_directory: android
        script: flutter build apk --no-sound-null-safety
    artifacts:
      - app/build/outputs/**/**/*.apk
